### ISSUE TITLE
Custom package variable name

### ISSUE THREAD

**Issue by idleberg** [yeoman/update-notifier#106]
This package doesn't allow me to specify a variable name for `package.json` of my liking.

**Example:**

```js
const meta = require('../package.json');
```

This will produce the following error:

```
/Users/me/my_package/node_modules/update-notifier/index.js:29
            throw new Error('pkg.name and pkg.version required');
            ^

Error: pkg.name and pkg.version required
    at new UpdateNotifier (/Users/me/my_package/node_modules/update-notifier/index.js:29:10)
    at module.exports.options (/Users/me/my_package/node_modules/update-notifier/index.js:143:25)
    at Object.<anonymous> (/Users/me/my_package/bin/cmd.js:12:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
```

**Comment by nexdrew** [comment]
@idleberg If you're passing it as `{ pkg }`, try passing `{ pkg: meta }` instead.
