### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by lukepighetti** [yeoman/update-notifier#144]
Hello, I am getting an error when building a project that uses `update-notifier` as a dependency. This error occurs on my Codeship pipeline, but not on my dev machine running Node 8 LTS. Do you have any recommendations for resolving this?

```
bolt: Generating lib/rules.json...

/home/rof/src/github.com/lukepighetti/when-coin-3/firebase/database/node_modules/firebase-bolt-compiler/node_modules/update-notifier/index.js:2
const spawn = require('child_process').spawn;
^^^^^
SyntaxError: Use of const in strict mode.
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/home/rof/src/github.com/lukepighetti/when-coin-3/firebase/database/node_modules/firebase-bolt-compiler/bin/firebase-bolt-compiler:2:24)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
```

**Comment by lukepighetti** [comment]
Was on a very old version of Node, nothing to see here.
