### ISSUE TITLE
TypeError: Cannot read property 'optOut' of null

### ISSUE THREAD

**Issue by desm** [yeoman/update-notifier#25]
I am getting the following exception when using 'nodemon' which uses 'update-notifier':

exception in nodemon killing node
TypeError: Cannot read property 'optOut' of null
at Object.Configstore.get (/usr/local/pkgs/node-v0.10.25-linux-x64/lib/node_modules/nodemon/node_modules/update-notifier/node_modules/configstore/configstore.js:83:17)
at UpdateNotifier.check (/usr/local/pkgs/node-v0.10.25-linux-x64/lib/node_modules/nodemon/node_modules/update-notifier/lib/update-notifier.js:47:18)
at module.exports (/usr/local/pkgs/node-v0.10.25-linux-x64/lib/node_modules/nodemon/node_modules/update-notifier/lib/update-notifier.js:142:17)
at Object. (/usr/local/pkgs/node-v0.10.25-linux-x64/lib/node_modules/nodemon/bin/nodemon.js:7:16)
at Module.compile (module.js:456:26)
at Object.Module.extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)

After more testing, I am able to reproduce this error. It is happening on an AWS EC2 micro instance, when I try to fire up 5 different node processes simultaneously from a bash script. Something like:

cd scriptdir1 && nodemon script1 > /var/log/script1.log 2>&1 &
cd scriptdir2 && nodemon script2 > /var/log/script2.log 2>&1 &
cd scriptdir3 && nodemon script3 > /var/log/script3.log 2>&1 &
cd scriptdir4 && nodemon script4 > /var/log/script4.log 2>&1 &
cd scriptdir5 && nodemon script5 > /var/log/script5.log 2>&1 &

Usually, 2 out of the 5 log files will simply contain the exception shown in previous comment.

If I tinker a little in order to space out the firing up of the nodemon processes using 'sleep' like this:

sleep .0 && cd scriptdir1 && nodemon script1 > /var/log/script1.log 2>&1 &
sleep .1 && cd scriptdir2 && nodemon script2 > /var/log/script2.log 2>&1 &
sleep .2 && cd scriptdir3 && nodemon script3 > /var/log/script3.log 2>&1 &
sleep .3 && cd scriptdir4 && nodemon script4 > /var/log/script4.log 2>&1 &
sleep .4 && cd scriptdir5 && nodemon script5 > /var/log/script5.log 2>&1 &

Then I never get the error.

Note: I have also posted this issue with 'nodemon'.

**Comment by wamoyo** [comment]
I still have this issue on 0.3.2. Same as @niftylettuce above. Sometimes it'll say `Cannot read property of 'lastUpdateCheck' of null` instead.
